# Generated by Django 6.0.2 on 2026-05-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_tag_product_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
    ]
