# Generated by Django 6.0.2 on 2026-05-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"], "verbose_name_plural": "Tags"},
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
