# Generated by Django 6.0.2 on 2026-05-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
